name: byte_me
description: A cohesive, high-performance download engine for Dart/Flutter with HLS and remuxing support.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  encrypt: ^5.0.3
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
